language: python
python:
  - "2.7"
install:
  - pip install -r dev_requirements.txt
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report -m --fail-under 90
after_success:
  coveralls
notifications:
  email:
    - ci-notify@openlabs.co.in
