language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - python setup.py install
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report -m --fail-under 90
after_success:
  coveralls
notifications:
  email:
    - ci-notify@openlabs.co.in
